#define             VAR             1
#define             CONST           2
#define             IF              3
#define             ELSE            4
#define             WHILE           5
#define             PRINT           6
#define             READ            7
#define             STRING          8
#define             ID              9
#define             INTLITERAL      10
#define             LPAREN          11
#define             RPAREN          12
#define             SEMICOLON       13
#define             COMMA           14
#define             ASSIGNOP        15
#define             PLUSOP          16
#define             MINUSOP         17
#define             REALLIT         18
#define             DIVISION        19
#define             MULTIPLICATION  20
#define             LEFTKEY         21
#define             RIGHTKEY        22