#define             VAR             1
#define             CONST           2
#define             IF              3
#define             ELSE            4
#define             WHILE           5
#define             PRINT           6
#define             READ            7
#define             ID              8
#define             INTLITERAL      9
#define             LPAREN          10
#define             RPAREN          11
#define             SEMICOLON       12
#define             COMMA           13
#define             ASSIGNOP        14
#define             PLUSOP          15
#define             MINUSOP         16
#define             REALLIT         17
#define             DIVISION        18
#define             MULTIPLICATION  19
#define             LEFTKEY         20
#define             RIGHTKEY        21