#define			VOID			1	
#define			VAR			2
#define			CONST			3
#define			IF			4
#define			ELSE			5
#define			WHILE			6
#define			PRINT			7
#define			READ			8
#define			PCOMMA			9
#define			COMMA			10
#define			PLUSOP			11
#define 			MINUSOP		12
#define			ASTER			13
#define			BARRA			14
#define			ASSIG			15
#define			PARI			16
#define			PARD			17
#define			CORI			18
#define			CORD			19
#define 			ENT			20
#define 			ID			21
#define			CADE			22
